export default {
   TRIGGER_ACTION: 'TRIGGER_ACTION',
   DIFFERENT_ACTION: 'DIFFERENT_ACTION',
   ADD_ITEM: 'ADD_ITEM',
   EDIT_ITEM: 'EDIT_ITEM',
   DELETE_ITEM: 'DELETE_ITEM',
   SELECT_ITEM: 'SELECT_ITEM',
   LOAD_ITEMS: 'LOAD_ITEMS',
   CLEAR_ITEMS: 'CLEAR_ITEMS'
};
