export default {
   TRIGGER_ACTION: 'TRIGGER_ACTION',
   DIFFERENT_ACTION: 'DIFFERENT_ACTION',

   // ITEMS
   ADD_ITEM: 'ADD_ITEM',
   EDIT_ITEM: 'EDIT_ITEM',
   DELETE_ITEM: 'DELETE_ITEM',
   SELECT_ITEM: 'SELECT_ITEM',
   LOAD_ITEMS: 'LOAD_ITEMS',
   CLEAR_ITEMS: 'CLEAR_ITEMS',

   // TAGS
   ADD_TAG: 'ADD_TAG',
   EDIT_TAG: 'EDIT_TAG',
   DELETE_TAG: 'DELETE_TAG',
   SELECT_TAG: 'SELECT_TAG',
   LOAD_TAGS: 'LOAD_TAGS'
};
